### ISSUE TITLE
possible strategie (oppinions?)

### ISSUE THREAD

**Issue by HeIIow2** [ArchiveTeam/imgur-grab#1]
I will help archive stuff, but I don't have own infrastructure, nor do I wanna host random porn images, due to *cp*.

I will build a bot, scraping nsfw subreddits, and when an imgur link is found, it uploads it to [catbox](https://catbox.moe/), and then saves the imgur link and catbox link in a database.

```
# Headers
Request URL: https://catbox.moe/user/api.php
Request Method: POST
Status Code: 200 
Remote Address: 107.160.74.131:443
Referrer Policy: strict-origin-when-cross-origin

# Payload
reqtype: urlupload
userhash: 
url: https://i.imgur.com/REDACTED.png

# Response
https://files.catbox.moe/REDACTED.png
```

So as you can see that is really easy to acomplish.

Then I will make a browser extention, that just replaces imgur links on reddit.

The question is... Should I just make a PR in this repository?
EDIT: need to be able to fork the repo if you want a pr

**Comment by Arkiver2** [comment]
Thank you for the suggestion! Please join us in #imgone on hackint for further discussions.

**Comment by HeIIow2** [comment]
I did, and according to someone there reddit is covered. Thus I will confirm the subs I want with my own scrapers, and then make a browser extensions, to replace broken imgur links.

<333
