### ISSUE TITLE
`Lua runtime error: JSON.lua:383: nil passed to JSON:decode().` on NSFW images

### ISSUE THREAD

**Issue by JustAnotherArchivist** [ArchiveTeam/imgur-grab#2]
NSFW images with the age gate throw that error and fail the item.

Examples from the channel (NSFW, duh...):
https://imgur.com/axpWR
https://imgur.com/urr2hBw
https://imgur.com/BUpTKtS

**Comment by Arkiver2** [comment]
Fixed with https://github.com/ArchiveTeam/imgur-grab/commit/5208ddb20db2c768adf0a9504b1dbeb46449b2d3
