### ISSUE TITLE
Installation Issue on Ubuntu 22.04

### ISSUE THREAD

**Issue by zenmindai** [ArchiveTeam/imgur-grab#3]
Using the instructions shown here, I am unable to get the `libzstd-dev=1.4.4` to replace my current `libzstd-dev=1.4.8`

> `adduser --system --group --shell /bin/bash archiveteam
echo deb http://deb.debian.org/debian buster-backports main contrib > /etc/apt/sources.list.d/backports.list
apt-get update \
&& apt-get install -y git-core libgnutls-dev lua5.1 liblua5.1-0 liblua5.1-0-dev screen bzip2 zlib1g-dev flex autoconf autopoint texinfo gperf lua-socket lua-filesystem lua-sec lua-zip rsync automake pkg-config python3-dev python3-pip build-essential poppler-utils \
&& apt-get -t buster-backports install zstd libzstd-dev libzstd1
python3 -m pip install setuptools wheel
python3 -m pip install --upgrade seesaw zstandard requests
su -c "cd /home/archiveteam; git clone https://github.com/ArchiveTeam/imgur-grab.git; cd imgur-grab; ./get-wget-lua.sh" archiveteam
screen su -c "cd /home/archiveteam/imgur-grab/; run-pipeline3 pipeline.py --concurrent 2 --address '127.0.0.1' YOURNICKHERE" archiveteam
[... ctrl+A D to detach ...]`

`apt-get` has an error for ` apt-get -t buster-backports install zstd libzstd-dev libzstd1` . I've tried install individual packages such as `libzstd1` or replacing `install` with `reinstall` but I cannot get `apt-get` to install `libzstd-dev=1.4.4` and its dependencies over Ubuntu 22.04 existing packages.  There is always a warning that 

> `Some packages could not be installed. This may mean that you have requested an impossible situation or if you are using the unstable distribution that some required packages have not yet been created or been moved out of Incoming.`

Then it proceeds to tell me I have a newer version or `libzstd-dev=1.4.4` has to have `libzstd1=1.4.4` installed first.

Is there an override this warning and have `apt-get` install the old version? Especially install `libzstd1=1.4.4` ? It seems I need to install that FIRST to meet the dependency for `libzstd-dev=1.4.4`.

**Comment by TheTechRobo** [comment]
It's not recommended to build Wget+At yourself. Use the Docker containers instead if at all possile.

**Comment by Arkiver2** [comment]
Currently only Zstd 1.4.4 is supported. This will now not be changed. I do expect newer versions of Zstd to be supported in the near future, likely on other project.

As @TheTechRobo noted, please use Docker.
