### ISSUE TITLE
Banned IP resulting in warrior claiming task and failing them really fast

### ISSUE THREAD

**Issue by IDKhowToScript** [ArchiveTeam/imgur-grab#4]
When an IP is banned, such as 429, the item gets aborted and next item gets claimed without waiting time, resulting in lots of claims that will never gets finished. 

There is currently no wait time between each task if 429 is seen, maybe put a 600 second sleep once an item gets 429

**Comment by danielloader** [comment]
Yeah not a clue how long the 429 expects me to back off since their response headers don't include a useful retry-after value to delay more requests...

**Comment by Arkiver2** [comment]
Fixed with https://github.com/ArchiveTeam/imgur-grab/commit/f4298e17659adad418ae96270c03a9f17851fad5
